### ISSUE TITLE
Invalid certificate served by next.projectreactor.io

### ISSUE THREAD

**Issue by andreild** [reactor/projectreactor.io#41]
The website https://next.projectreactor.io uses an invalid HTTPS certificate: its Common Name is `*.cfapps.io`, and it does not have any Subject Alternative Name entries.

This makes browsers mark the certificate as invalid.

Edit: I notice (of course only after creating this ticket) that https://github.com/reactor/reactor-netty would have been a better location to file this bug. Can this be moved?

![invalid_cert_next projectreactor io](https://user-images.githubusercontent.com/17121633/59250617-14f9b380-8c28-11e9-9fdf-bd5d1f781ac4.png)

**Comment by bsideup** [comment]
@andreild thanks for reporting!
`next.*` is our internal (staging) environment for the website and we do not provide any guarantees about it (unlike the main website).

This is definitely not reactor-netty's problem, just the SSL termination has the generic CloudFoundry's certificate since we're hosting our website on [Pivotal Web Services](https://run.pivotal.io).
