### ISSUE TITLE
Link to Kotlin API Is Broken (404)

### ISSUE THREAD

**Issue by philipbel** [reactor/projectreactor.io#42]
## Expected Behavior
On the [Documentation page](https://projectreactor.io/docs), the [Kotlin Doc](https://projectreactor.io/docs/core/release/kdoc-api/) should show the Kotlin API.

## Actual Behavior
The link shows a 404.

## Steps to Reproduce

1. Open the [Documentation page](https://projectreactor.io/docs).
2. Click on the [Kotlin Doc](https://projectreactor.io/docs/core/release/kdoc-api/) link under Reactor Core / Javadoc.

**Comment by simonbasle** [comment]
Thanks for reporting this. I'll remove the link to kotlin docs in the `core` section, since the extensions have now been extracted into a separate project (see [the release notes](https://github.com/reactor/reactor-core/releases/tag/v3.3.0.RELEASE)).

Unfortunately, please note that we're unable to publish KDoc at this time due to a bug in the Dokka tool. See https://github.com/reactor/reactor-kotlin-extensions/issues/3

**Comment by simonbasle** [comment]
In the meantime, please refer to the javadoc version of kotlin extensions: https://projectreactor.io/docs/kotlin/release/api/

**Comment by philipbel** [comment]
Thanks for the info, Simon!
Not a huge issue; just not nice getting a 404.
